
ASSOCIATE(Left,SDL_BUTTON_LEFT,"Left")
ASSOCIATE(Middle,SDL_BUTTON_MIDDLE,"Middle")
ASSOCIATE(Right,SDL_BUTTON_RIGHT,"Right")
ASSOCIATE(WheelUp,SDL_BUTTON_WHEELUP,"WheelUp")
ASSOCIATE(WheelDown,SDL_BUTTON_WHEELDOWN,"WheelDown")
